name: shared_preference_sample
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  # dio: ^5.4.3+1
  # envied: ^0.5.4+1
  derry: ^1.5.0
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_riverpod: ^2.5.1
  # flutter_secure_storage: ^4.2.1
  # flutter_web_auth_2: ^3.1.1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  # go_router: ^14.1.0
  hooks_riverpod: ^2.5.1
  # isar: ^2.1.4
  json_annotation: ^4.9.0
  logger: ^2.2.0
  mockito: ^5.4.4
  # path_provider: ^2.0.15
  riverpod_annotation:
  shared_preferences: ^2.2.3
  # url_launcher: ^6.2.6
  # uuid: ^4.4.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.9
  # envied_generator:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  # go_router_builder: ^2.6.2
  json_serializable: ^6.8.0
  riverpod_generator:
  riverpod_lint:

flutter:
  # assets:
  #   - assets/hoge.png
  uses-material-design: true

scripts:
  # build_runnerを実行して、同じファイル名があれば古いものを削除する
  br: flutter pub run build_runner build --delete-conflicting-outputs
  #  Gradle デーモンプロセスを終了する => ビルドエラーの解消
  gc: pkill -f '.*GradleDaemon.*'
  # テストを実行しカバレッジをHTMLで出力してブラウザで開くスクリプト
  cov: flutter test --coverage && lcov --remove coverage/lcov.info 'lib/**.g.dart' -o coverage/new_lcov.info --ignore-errors unused && genhtml coverage/new_lcov.info -o coverage/html && open coverage/html/index.html
